version: "3.8"

services:
  flask_app:
    container_name: flask_app-Seatapp
    build: ./main
    ports: 
      - "5000:50505"
    environment:
      - DB_URL=postgresql://postgre:porec777B@des.postgres.database.azure.com:5432/postgres
      - DEBUGGER=True
      - FLASK_DEBUG=1  # Enable debug mode
      - FLASK_ENV=development
