version: "3.3"

services:
  postgres_db:
    container_name: postgres_db-Seatapp
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask_app-Seatapp
    build: ./main
    ports: 
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - DEBUGGER=True
      - FLASK_DEBUG=1  # Enable debug mode
      - FLASK_ENV=development
    depends_on:
      - postgres_db
    volumes: 
      - ./main:/app

volumes:
  pgdata: